### ISSUE TITLE
Lots of errors/warnings when installing on Windows 7

### ISSUE THREAD

**Issue by mainman** [stackgl/shader-school#128]
Here is the trace :
```
$ npm install -g shader-school
npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.2.1
/


> canvas@1.2.3 install C:\Users\Renaud\AppData\Roaming\npm\node_modules\shader-sc
hool\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browser
ify\node_modules\canvas
> node-gyp rebuild

\
C:\Users\Renaud\AppData\Roaming\npm\node_modules\shader-school\node_modules\gl-ax
es\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas
not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\b
in\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (re
build)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.3.0, which is not supporte
d by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\npm
\node_modules\node-gyp\lib\configure.js:108:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-
gyp\lib\configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modul
es\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Renaud\AppData\Roaming\npm\node_modules\shader-school\node_
modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_m
odules\canvas
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing canvas@1.2.3
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.3",
"npm":"2.9.1"})
/


> stanford-dragon@1.1.1 postinstall C:\Users\Renaud\AppData\Roaming\npm\node_modu
les\shader-school\node_modules\stanford-dragon
> npm run build

|
> stanford-dragon@1.1.1 build C:\Users\Renaud\AppData\Roaming\npm\node_modules\sh
ader-school\node_modules\stanford-dragon
> npm run res1 && npm run res2 && npm run res3 && npm run res4

\
> stanford-dragon@1.1.1 res1 C:\Users\Renaud\AppData\Roaming\npm\node_modules\sha
der-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip.ply.gz 1.js

parsing ply file
unpacking positions
generating module
writing module
-
> stanford-dragon@1.1.1 res2 C:\Users\Renaud\AppData\Roaming\npm\node_modules\sha
der-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res2.ply.gz 2.js

parsing ply file
unpacking positions
generating module
writing module
\
> stanford-dragon@1.1.1 res3 C:\Users\Renaud\AppData\Roaming\npm\node_modules\sha
der-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res3.ply.gz 3.js

parsing ply file
unpacking positions
generating module
writing module
|
> stanford-dragon@1.1.1 res4 C:\Users\Renaud\AppData\Roaming\npm\node_modules\sha
der-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res4.ply.gz 4.js

parsing ply file
unpacking positions
generating module
writing module
C:\Users\Renaud\AppData\Roaming\npm\shader-school -> C:\Users\Renaud\AppData\Roam
ing\npm\node_modules\shader-school\index.js
shader-school@1.1.0 C:\Users\Renaud\AppData\Roaming\npm\node_modules\shader-schoo
l
├── remove-element@0.0.0
├── google-fonts@0.0.0
├── zfill@0.0.2
├── domify@1.3.3
├── right-now@1.0.0
├── sidenote@1.0.0
├── findup-element@0.0.0
├── canvas-fit@0.0.0
├── gl-fbo-matching@1.0.0
├── quotemeta@0.0.0
├── clamp@1.0.1
├── opener@1.4.1
├── glsldoc@0.0.4
├── insert-css@0.1.1
├── sliced@0.0.5
├── wordwrap@0.0.2
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── marked@0.3.3
├── frame-debounce@0.0.0 (raf-component@1.1.2)
├── gl-context@0.1.1 (raf-component@1.1.2)
├── memoize-sync@0.0.2 (strip@0.0.0)
├── raf@2.0.4 (performance-now@0.1.4)
├── mesh-normals@1.0.0 (unindex-mesh@0.0.0, normals@0.1.0, face-normals@0.0.0)
├── ndarray@1.0.18 (iota-array@1.0.0, is-buffer@1.0.2)
├── mouse-pressed@0.0.1 (events@1.0.2)
├── mouse-position@1.0.0 (events@1.0.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── gl-compare@1.0.0 (canvas-pixels@0.0.0)
├── apprise@1.0.0 (emitter-component@1.1.1, once@1.3.2)
├── gl-compare-sidebar@1.1.4 (escape-html@1.0.1, inherits@2.0.1, range-slider@1.0
.2, events@1.0.2)
├── gl-vao@1.2.0 (webglew@1.0.5)
├── gl-fbo@1.1.3 (webglew@1.0.5)
├── browser-menu@0.1.0 (vkey@0.0.3, xtend@2.2.0, events@1.0.2, terminal-menu@0.2.
0)
├── gl-texture2d@1.2.0 (webglew@1.0.5, typedarray-pool@1.1.0, ndarray-ops@1.2.2)
├── gl-buffer@2.1.1 (webglew@1.0.5, typedarray-pool@1.1.0, ndarray-ops@1.2.2)
├── a-big-triangle@0.0.0 (gl-vao@0.0.3, gl-buffer@0.1.2)
├── rework-npm@0.6.1 (css-parse@1.7.0, resolve@0.6.3)
├── conway-hart@0.1.0
├── gl-matrix@2.1.0
├── ecstatic@0.5.8 (mime@1.3.4, minimist@1.1.1, he@0.5.0)
├── xhr@1.17.1 (once@1.1.1, global@4.3.0, parse-headers@2.0.0)
├── rework-inline@0.2.0 (parse-import@0.1.3, find-file@0.1.4, css@1.6.0)
├── rework@0.20.3 (hsb2rgb@1.0.2, rework-visit@1.0.0, color-parser@0.1.0, rework-
inherit@0.2.3, convert-source-map@0.3.5, mime@1.2.11, debug@2.2.0, css@1.6.0)
├── ndarray-distance@0.0.0 (cwise@0.4.0)
├── highlight.js@8.6.0
├── brfs@1.4.0 (quote-stream@0.0.0, through2@0.4.2, resolve@1.1.6, static-module@
1.1.2)
├── envify@1.2.1 (through@2.3.7, xtend@2.1.2, jstransform@3.0.0, esprima-fb@3001.
1.0-dev-harmony-fb)
├── beefy@2.1.5 (leftpad@0.0.0, ansicolors@0.3.2, pretty-bytes@0.1.2, ignorepatte
rns@1.0.1, find-global-packages@0.0.1, which@1.0.9, response-stream@0.0.0, throug
h@2.2.7, open@0.0.3, minimist@0.0.8, mime@1.2.11, xtend@2.1.2, portfinder@0.2.1,
readable-stream@1.0.33, resolve@0.6.3, concat-stream@1.4.8, chokidar@1.0.1, scrip
t-injector@1.0.0)
├── gl-axes@2.3.0 (extract-frustum-planes@1.0.0, bit-twiddle@1.0.2, gl-state@1.0.
0, split-polygon@1.0.0, vectorize-text@2.0.4)
├── inquirer@0.5.1 (mute-stream@0.0.4, through@2.3.7, async@0.8.0, readline2@0.1.
1, lodash@2.4.2, cli-color@0.3.3)
├── browserify@6.3.4 (https-browserify@0.0.0, tty-browserify@0.0.0, inherits@2.0.
1, isarray@0.0.1, commondir@0.0.1, builtins@0.0.7, string_decoder@0.10.31, consta
nts-browserify@0.0.1, path-browserify@0.0.0, process@0.8.0, os-browserify@0.1.2,
xtend@3.0.0, defined@0.0.0, shallow-copy@0.0.1, stream-browserify@1.0.0, shell-qu
ote@0.0.1, domain-browser@1.1.4, deep-equal@0.2.2, querystring-es3@0.2.1, assert@
1.1.2, punycode@1.2.4, util@0.10.3, events@1.0.2, vm-browserify@0.0.4, parents@0.
0.3, subarg@1.0.0, console-browserify@1.1.0, readable-stream@1.0.33, timers-brows
erify@1.4.1, resolve@0.7.4, duplexer2@0.0.2, through2@1.1.1, http-browserify@1.7.
0, concat-stream@1.4.8, shasum@1.0.1, url@0.10.3, buffer@2.8.2, glob@4.5.3, label
ed-stream-splicer@1.0.2, JSONStream@0.8.4, syntax-error@1.1.4, browser-resolve@1.
9.0, deps-sort@1.3.9, browser-pack@3.2.0, browserify-zlib@0.1.4, crypto-browserif
y@3.9.14, insert-module-globals@6.5.0, module-deps@3.8.0, umd@2.1.0)
├── baboon-image@1.0.0 (ndpack-image@1.0.4)
├── autoprefixer@1.3.1 (postcss@0.3.5, fs-extra@0.9.1, caniuse-db@1.0.30000180)
├── stanford-dragon@1.1.1 (parse-ply@0.1.0, map-limit@0.0.0, glob@3.2.11)
├── glslify@1.6.0 (cssauron-glsl@0.0.0, emit-function@0.0.2, shortest@0.0.0, cssa
uron@0.0.2, through@2.3.7, gl-shader-core@2.2.0, glsl-min-stream@0.0.2, glsl-depa
rser@0.0.2, nopt@2.2.1, resolve@0.6.3, new-from@0.0.3, concat-stream@1.4.8, glsli
fy-stream@0.4.1, glsl-extract@0.0.2, esprima@1.2.5, static-eval@0.2.4, sleuth@0.0
.0, replace-method@0.0.0)
└── glslify-live@2.1.0 (through@2.3.7, once@1.3.2, uuid@1.4.2, events@1.0.2, sse-
stream@0.0.4, sleuth@0.1.1, glsl-resolve@0.0.1, chokidar@0.8.4, glslify-bundle@1.
0.3, gl-shader-update@0.0.0, esprima@1.2.5, static-eval@0.2.4, request@2.55.0, en
vify@2.0.1, replace-method@0.0.0)

```

**Comment by dy-dx** [comment]
@mainman Those errors are for an optional dependency, so you should be fine.
