### ISSUE TITLE
Cannot install shader-school on 10.10.3 OSX machine

### ISSUE THREAD

**Issue by grimepoch** [stackgl/shader-school#133]
I have spent probably four hours trying to figure out why I cannot install shader-school on my machine.  It seems to have a problem not finding this file:

npm ERR! path /usr/local/lib/node_modules/shader-school/node_modules/glslify/node_modules/replace-method/node_modules/recast/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT

But, if I dig deeper, I think it cannot install this possibly?

glslify

**Comment by dy-dx** [comment]
This is a new issue. I'm so sorry you spent hours on this! I'm looking into it.

**Comment by grimepoch** [comment]
Hey, I'm just glad to know that it wasn't me! Thanks for looking into it.

**Comment by dy-dx** [comment]
https://github.com/hughsk/replace-method/issues/1

This dependency will have to be updated in replace-method (https://github.com/hughsk/replace-method/blob/8eb35598740550126d245b7077cd3dbbeb5bb45a/package.json#L8)
and then https://github.com/hughsk/glslify-live/blob/350ed78d6678f9afa4a174077293ce0fbed7bd48/package.json#L30 will have to be updated as well

**Comment by grimepoch** [comment]
Is there something I can do to install this our do I need to wait for the dependency to be updated?

**Comment by dy-dx** [comment]
@grimepoch It should be working again.

**Comment by zzz6519003** [comment]
I have same kind of issue on both windows & mac...

**Comment by dy-dx** [comment]
@zzz6519003 It's working for me on mac. If the errors you're seeing are for optional dependencies, then it's ok to ignore them.

**Comment by zzz6519003** [comment]
you look awesome

**Comment by dy-dx** [comment]
@zzz6519003 Thanks! Does it work for you now?

**Comment by zzz6519003** [comment]
```
➜  react-things  sudo npm install -g shader-school
Password:
npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm ERR! fetch failed https://registry.npmjs.org/caniuse-db/-/caniuse-db-1.0.30000243.tgz
npm WARN retry will retry, error on last attempt: Error: getaddrinfo ENOTFOUND registry.npmjs.org
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.11.16","npm":"2.10.1"})
 
> fsevents@0.3.6 install /usr/local/lib/node_modules/shader-school/node_modules/beefy/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
 
> canvas@1.2.4 install /usr/local/lib/node_modules/shader-school/node_modules/gl-axes/node_modules/vectorize-text/node_modules/canvas-browserify/node_modules/canvas
> node-gyp rebuild

./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/shader-school/node_modules/gl-axes/node_modules/vectorize-text/node_modules/canvas-browserify/node_modules/canvas
gyp ERR! node -v v0.11.16
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing canvas@1.2.4
 
> stanford-dragon@1.1.1 postinstall /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> npm run build

-
> stanford-dragon@1.1.1 build /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> npm run res1 && npm run res2 && npm run res3 && npm run res4

|
> stanford-dragon@1.1.1 res1 /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> node lib/build.js models/dragon_vrip.ply.gz 1.js

parsing ply file
unpacking positions
generating module
writing module
|
> stanford-dragon@1.1.1 res2 /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> node lib/build.js models/dragon_vrip_res2.ply.gz 2.js

parsing ply file
unpacking positions
generating module
writing module
-
> stanford-dragon@1.1.1 res3 /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> node lib/build.js models/dragon_vrip_res3.ply.gz 3.js

parsing ply file
unpacking positions
generating module
writing module
|
> stanford-dragon@1.1.1 res4 /usr/local/lib/node_modules/shader-school/node_modules/stanford-dragon
> node lib/build.js models/dragon_vrip_res4.ply.gz 4.js

parsing ply file
unpacking positions
generating module
writing module

```

then it hang up like forever...

**Comment by abacon** [comment]
@dy-dx I've made a PR into hughsk/glslify-live#3 to fix the issue there.
