### ISSUE TITLE
"Hello, GLSL" crashes server immediately

### ISSUE THREAD

**Issue by erhhung** [stackgl/shader-school#140]
What a start to the course! The project installs on OS X flawlessly and starts as expected, but as soon as I select the first lesson "Hello, GLSL", the page goes black until I figured out that the server has crashed:

````
WORKSHOP URL: http://localhost:12492

200   11ms       299B  /
200  399ms    71.28KB  /index.js ➞ /usr/local/lib/node_modules/shader-school/node_modules/browserify ./index.js -d
200    3ms       282B  /

/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/quote-stream/index.js:70
                if (rawBuf.equals(multiByteBuffers.lineSeparator)) {
                           ^
TypeError: Object – has no method 'equals'
    at DestroyableTransform.write [as _transform] (/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/quote-stream/index.js:70:28)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/usr/local/lib/node_modules/shader-school/node_modules/brfs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/shader-school/node_modules/
````

I'm using Node v0.10.38.

**Comment by mattdesl** [comment]
Try upgrading node to a newer version. I just tested on v4.0.0.
