### ISSUE TITLE
Install Fails on Windows (10)

### ISSUE THREAD

**Issue by computersarecool** [stackgl/shader-school#146]
I do not see any way to get around the gyp error.  I am trying to install on Windows 10, here is the output:

Running
```
$ npm install -g shader-school --python=python2.7 > error.log
```

Outputs this to stdout:
```
npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"4.2.1",
"npm":"2.14.8"})
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "reb
uild"
gyp ERR! cwd C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node
_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node
_modules\canvas
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
parsing ply file
unpacking positions
generating module
writing module
parsing ply file
unpacking positions
generating module
writing module
parsing ply file
unpacking positions
generating module
writing module
parsing ply file
unpacking positions
generating module
writing module
npm WARN optional dep failed, continuing canvas@1.3.1

```
And this to the logfile
```
> canvas@1.3.1 install C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas
> node-gyp rebuild


C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas>if not defined npm_config_node_gyp (node "c:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Warning: Missing input files:
C:\GTK\bin\zlib1.dll
C:\GTK\bin\libexpat-1.dll
C:\GTK\bin\libpng14-14.dll
C:\GTK\bin\libcairo-2.dll
C:\GTK\bin\libfontconfig-1.dll
C:\GTK\bin\libfreetype-6.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Canvas.cc
  CanvasGradient.cc
  CanvasPattern.cc
  CanvasRenderingContext2d.cc
  color.cc
  Image.cc
  ImageData.cc
  init.cc
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasPattern.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\CanvasPattern.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\CanvasPattern.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Image.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\Image.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\Image.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasGradient.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\CanvasGradient.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\CanvasGradient.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\Canvas.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\Canvas.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\Canvas.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\color.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\color.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\color.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\init.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\init.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\init.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\ImageData.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\ImageData.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\ImageData.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): note: command-line arguments:  see previous definition of 'snprintf' (compiling source file ..\src\CanvasRenderingContext2d.cc)
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\CanvasRenderingContext2d.cc) [C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\gl-axes\node_modules\vectorize-text\node_modules\canvas-browserify\node_modules\canvas\build\canvas.vcxproj]

> stanford-dragon@1.1.1 postinstall C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> npm run build


> stanford-dragon@1.1.1 build C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> npm run res1 && npm run res2 && npm run res3 && npm run res4


> stanford-dragon@1.1.1 res1 C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip.ply.gz 1.js


> stanford-dragon@1.1.1 res2 C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res2.ply.gz 2.js


> stanford-dragon@1.1.1 res3 C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res3.ply.gz 3.js


> stanford-dragon@1.1.1 res4 C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\node_modules\stanford-dragon
> node lib/build.js models/dragon_vrip_res4.ply.gz 4.js

C:\Users\willy\AppData\Romaning\npm\shader-school -> C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school\index.js
shader-school@1.1.0 C:\Users\willy\AppData\Romaning\npm\node_modules\shader-school
├── glsldoc@0.0.4
├── remove-element@0.0.0
├── domify@1.4.0
├── zfill@0.0.2
├── right-now@1.0.0
├── gl-fbo-matching@1.0.0
├── sidenote@1.0.0
├── findup-element@0.0.0
├── canvas-fit@0.0.0
├── clamp@1.0.1
├── google-fonts@0.0.0
├── opener@1.4.1
├── quotemeta@0.0.0
├── insert-css@0.1.1
├── wordwrap@0.0.2
├── gl-vao@1.2.1
├── sliced@0.0.5
├── marked@0.3.5
├── memoize-sync@0.0.2 (strip@0.0.0)
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── frame-debounce@0.0.0 (raf-component@1.1.2)
├── gl-context@0.1.1 (raf-component@1.1.2)
├── ndarray@1.0.18 (iota-array@1.0.0, is-buffer@1.1.0)
├── mesh-normals@1.0.0 (normals@0.1.0, unindex-mesh@0.0.0, face-normals@0.0.0)
├── raf@2.0.4 (performance-now@0.1.4)
├── gl-compare@1.0.0 (canvas-pixels@0.0.0)
├── conway-hart@0.1.0
├── mouse-pressed@0.0.1 (events@1.1.0)
├── mouse-position@1.0.0 (events@1.1.0)
├── gl-fbo@1.1.3 (webglew@1.0.5)
├── apprise@1.0.0 (emitter-component@1.1.1, once@1.3.2)
├── gl-compare-sidebar@1.1.4 (escape-html@1.0.3, inherits@2.0.1, range-slider@1.0.2, events@1.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── gl-matrix@2.3.1
├── gl-texture2d@1.2.0 (webglew@1.0.5, typedarray-pool@1.1.0, ndarray-ops@1.2.2)
├── gl-buffer@2.1.2 (typedarray-pool@1.1.0, ndarray-ops@1.2.2)
├── browser-menu@0.1.0 (vkey@0.0.3, xtend@2.2.0, events@1.1.0, terminal-menu@0.2.0)
├── a-big-triangle@0.0.0 (gl-vao@0.0.3, gl-buffer@0.1.2)
├── ndarray-distance@0.0.0 (cwise@0.4.0)
├── ecstatic@0.5.8 (he@0.5.0, mime@1.3.4, minimist@1.2.0)
├── rework-npm@0.6.1 (css-parse@1.7.0, resolve@0.6.3)
├── xhr@1.17.1 (once@1.1.1, parse-headers@2.0.1, global@4.3.0)
├── envify@1.2.1 (through@2.3.8, xtend@2.1.2, esprima-fb@3001.1.0-dev-harmony-fb, jstransform@3.0.0)
├── rework-inline@0.2.0 (parse-import@0.1.3, find-file@0.1.4, css@1.6.0)
├── rework@0.20.3 (hsb2rgb@1.0.2, rework-visit@1.0.0, rework-inherit@0.2.3, mime@1.2.11, color-parser@0.1.0, convert-source-map@0.3.5, debug@2.2.0, css@1.6.0)
├── baboon-image@1.0.1 (ndpack-image@1.0.4)
├── highlight.js@8.9.1
├── brfs@1.4.1 (quote-stream@1.0.2, through2@2.0.0, resolve@1.1.6, static-module@1.1.3)
├── gl-axes@2.3.0 (extract-frustum-planes@1.0.0, bit-twiddle@1.0.2, gl-state@1.0.0, split-polygon@1.0.0, vectorize-text@2.0.4)
├── beefy@2.1.5 (leftpad@0.0.0, ansicolors@0.3.2, find-global-packages@0.0.1, pretty-bytes@0.1.2, ignorepatterns@1.0.1, which@1.0.9, mime@1.2.11, open@0.0.3, through@2.2.7, response-stream@0.0.0, minimist@0.0.8, xtend@2.1.2, readable-stream@1.1.13, portfinder@0.2.1, concat-stream@1.5.1, resolve@0.6.3, chokidar@1.2.0, script-injector@1.0.0)
├── glslify@1.6.0 (cssauron-glsl@0.0.0, emit-function@0.0.2, shortest@0.0.0, cssauron@0.0.2, through@2.3.8, glsl-min-stream@0.0.2, gl-shader-core@2.2.0, glsl-deparser@0.0.2, esprima@1.2.5, nopt@2.2.1, new-from@0.0.3, resolve@0.6.3, concat-stream@1.5.1, static-eval@0.2.4, glsl-extract@0.0.2, glslify-stream@0.4.1, sleuth@0.0.0, replace-method@0.0.0)
├── glslify-live@2.1.1 (through@2.3.8, once@1.3.2, uuid@1.4.2, events@1.1.0, sleuth@0.1.1, sse-stream@0.0.4, esprima@1.2.5, glsl-resolve@0.0.1, static-eval@0.2.4, glslify-bundle@1.0.3, envify@2.0.1, gl-shader-update@0.0.0, chokidar@1.2.0, request@2.65.0, replace-method@0.0.0)
├── browserify@6.3.4 (https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, constants-browserify@0.0.1, builtins@0.0.7, string_decoder@0.10.31, isarray@0.0.1, process@0.8.0, inherits@2.0.1, os-browserify@0.1.2, commondir@0.0.1, stream-browserify@1.0.0, punycode@1.2.4, defined@0.0.0, domain-browser@1.1.4, assert@1.1.2, shell-quote@0.0.1, duplexer2@0.0.2, xtend@3.0.0, shallow-copy@0.0.1, deep-equal@0.2.2, querystring-es3@0.2.1, util@0.10.3, concat-stream@1.4.10, events@1.0.2, through2@1.1.1, parents@0.0.3, timers-browserify@1.4.1, vm-browserify@0.0.4, readable-stream@1.1.13, console-browserify@1.1.0, subarg@1.0.0, url@0.10.3, http-browserify@1.7.0, buffer@2.8.2, shasum@1.0.2, resolve@0.7.4, JSONStream@0.8.4, labeled-stream-splicer@1.0.2, glob@4.5.3, syntax-error@1.1.4, browserify-zlib@0.1.4, deps-sort@1.3.9, browser-resolve@1.10.1, browser-pack@3.2.0, umd@2.1.0, crypto-browserify@3.11.0, insert-module-globals@6.6.3, module-deps@3.9.1)
├── autoprefixer@1.3.1 (postcss@0.3.5, fs-extra@0.9.1, caniuse-db@1.0.30000359)
├── inquirer@0.5.1 (mute-stream@0.0.4, async@0.8.0, through@2.3.8, lodash@2.4.2, readline2@0.1.1, cli-color@0.3.3)
└── stanford-dragon@1.1.1 (parse-ply@0.1.0, map-limit@0.0.0, glob@3.2.11)
```

Please let me know if anyone else has any ideas. Thanks

**Comment by mattdesl** [comment]
I am getting install errors too on my OSX but it seems like everything is working fine when I actually run `shader-school`. Is this the same for you?

**Comment by computersarecool** [comment]
No - I get nothing. 
> 'shader-school' is not recognized as an internal or external command....
