### ISSUE TITLE
Failed installation on windows

### ISSUE THREAD

**Issue by NervenCid** [stackgl/shader-school#161]
Hello, i tried to install the package, but i get this error instead:

c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Im
age.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\canvas.vcx
proj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Ca
nvas.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\canvas.vc
xproj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Ca
nvasGradient.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\c
anvas.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Im
ageData.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\canvas
.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Ca
nvasPattern.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\ca
nvas.vcxproj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\in
it.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas\build\canvas.vcxp
roj]
c:\users\nerve\appdata\roaming\npm\node_modules\shader-school\node_modules\canvas\src\Canvas.h(19): fatal e
rror C1083: Cannot open include file: 'cairo.h': No such file or directory (compiling source file ..\src\Ca
nvasRenderingContext2d.cc) [C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canv
as\build\canvas.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\nerve\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nerve\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\shader-school\node_modules\canvas
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:canvas@1.4.0 canvas@1.4.0 install: `node-gyp rebuild`
npm WARN install:canvas@1.4.0 Exit status 1
C:\Users\nerve\AppData\Roaming\npm
`-- shader-school@1.1.1
  `-- glslify@1.6.1
    `-- replace-method@0.0.0
      `-- recast@0.5.27
        `-- esprima@1.1.0-dev-harmony  (git+https://github.com/ariya/esprima.git#a65a3eb93b9a5dce9a1184ca2d1bd0b184c6b8fd)

npm WARN optional Skipping failed optional dependency /shader-school/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

How can i fix it?

**Comment by DealPete** [comment]
my guess would be you need to install Cairo
https://cairographics.org/
